services:
  postgres:
    image: postgres:18-alpine
    container_name: film-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/test:/docker-entrypoint-initdb.d
    ports:
      - '${DATABASE_PORT}:5432'
    networks:
      - afisha-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: film-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - afisha-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    image: ghcr.io/smilix123/film-react-nest-backend:latest
    container_name: film-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      PORT: ${PORT}
      LOGGER_TYPE: ${LOGGER_TYPE}
    ports:
      - '${PORT}:3000'
    volumes:
      - ./backend/public/content:/app/public/content
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - afisha-network

  frontend:
    image: ghcr.io/smilix123/film-react-nest-frontend:latest
    container_name: film-frontend
    restart: unless-stopped
    volumes:
      - frontend_build:/build
    networks:
      - afisha-network

  nginx:
    image: ghcr.io/smilix123/film-react-nest-nginx:latest
    container_name: film-nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - frontend_build:/usr/share/nginx/html
      - ./backend/public/content:/usr/share/nginx/html/content
    depends_on:
      - backend
      - frontend
    networks:
      - afisha-network

  db-init:
    image: postgres:18-alpine
    container_name: film-db-init
    restart: 'no'
    depends_on:
      - postgres
    environment:
      PGPASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./backend/test:/sql
    entrypoint: |
      sh -c "
        echo 'Ожидание PostgreSQL...'
        until pg_isready -h postgres -U ${DATABASE_USERNAME}; do
          sleep 2
        done
        
        echo 'Создание таблиц...'
        psql -h postgres -U ${DATABASE_USERNAME} -d ${DATABASE_NAME} -f /sql/prac.init.sql
        
        echo 'Загрузка фильмов...'
        psql -h postgres -U ${DATABASE_USERNAME} -d ${DATABASE_NAME} -f /sql/prac.films.sql
        
        echo 'Загрузка расписания...'
        psql -h postgres -U ${DATABASE_USERNAME} -d ${DATABASE_NAME} -f /sql/prac.shedules.sql
        
        echo 'Инициализация базы данных завершена!'
      "
    networks:
      - afisha-network

volumes:
  postgres_data:
  pgadmin_data:
  frontend_build:

networks:
  afisha-network:
    driver: bridge
