services:
  postgres:
    image: postgres:18-alpine
    container_name: film-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '${DATABASE_PORT}:5432'
    networks:
      - afisha-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}']
      start_period: 30s
      interval: 10s
      timeout: 20s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: film-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - afisha-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    image: ghcr.io/${OWNER}/film-react-nest-backend:latest
    container_name: film-backend
    build:
      context: backend
    restart: unless-stopped
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      PORT: ${PORT}
      LOGGER_TYPE: ${LOGGER_TYPE}
    ports:
      - '${PORT}:3000'
    volumes:
      - ./backend/public/content:/app/public/content
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - afisha-network

  frontend:
    image: ghcr.io/${OWNER}/film-react-nest-frontend:latest
    container_name: film-frontend
    build:
      context: frontend
    restart: unless-stopped
    volumes:
      - frontend_build:/build
    networks:
      - afisha-network

  nginx:
    image: ghcr.io/${OWNER}/film-react-nest-nginx:latest
    container_name: film-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - frontend_build:/usr/share/nginx/html/frontend
      - ./backend/public/content:/usr/share/nginx/html/content
    depends_on:
      - backend
      - frontend
    networks:
      - afisha-network

volumes:
  postgres_data:
  pgadmin_data:
  frontend_build:

networks:
  afisha-network:
    driver: bridge
