services:
  postgres:
    image: postgres:18-alpine
    container_name: film-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '${DATABASE_PORT}:5432'
    networks:
      - afisha-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}']
      start_period: 30s
      interval: 10s
      timeout: 20s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: film-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - afisha-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    image: ghcr.io/${OWNER}/film-react-nest-backend:latest
    container_name: film-backend
    build:
      context: backend
    restart: unless-stopped
    environment:
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_URL: ${DATABASE_DRIVER}://database:${DATABASE_PORT}/${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      PORT: ${PORT}
      LOGGER_TYPE: ${LOGGER_TYPE}
    ports:
      - '${PORT}:3000'
    volumes:
      - ./backend/public/content:/app/public/content
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - afisha-network

  frontend:
    image: ghcr.io/${OWNER}/film-react-nest-frontend:latest
    container_name: film-frontend
    build:
      context: frontend
    environment:
      VITE_BASE_URL: /
      VITE_API_URL: ${VITE_API_URL}
      VITE_CDN_URL: ${VITE_CDN_URL}
    volumes:
      - frontend_build:/usr/share/nginx/html
    networks:
      - afisha-network
    healthcheck:
      test: ["CMD-SHELL", "test -f /usr/share/nginx/html/index.html && grep -q \"assets/\" /usr/share/nginx/html/index.html"]
      interval: 5s
      timeout: 2s
      retries: 20

  nginx:
    image: ghcr.io/${OWNER}/film-react-nest-nginx:latest
    container_name: film-nginx
    build:
      context: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./backend/public/content:/usr/share/nginx/html/content
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_healthy
    networks:
      - afisha-network

volumes:
  postgres_data:
  pgadmin_data:
  frontend_build:

networks:
  afisha-network:
    driver: bridge
